# Generated by Django 3.2.17 on 2023-10-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ventilator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.room')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.room')),
            ],
        ),
        migrations.CreateModel(
            name='WindowOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('isOpen', models.BooleanField()),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.window')),
            ],
        ),
        migrations.CreateModel(
            name='VentilatorIsOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('isOn', models.BooleanField()),
                ('ventilator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.ventilator')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleInRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('NOPeopleInRoom', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.room')),
            ],
        ),
        migrations.CreateModel(
            name='DoorOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('isOpen', models.BooleanField()),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.door')),
            ],
        ),
        migrations.AddField(
            model_name='door',
            name='rooms',
            field=models.ManyToManyField(to='project.Room'),
        ),
        migrations.AddConstraint(
            model_name='windowopen',
            constraint=models.UniqueConstraint(fields=('timestamp', 'window'), name='unique_timestamp_window_combination'),
        ),
        migrations.AddConstraint(
            model_name='ventilatorison',
            constraint=models.UniqueConstraint(fields=('timestamp', 'ventilator'), name='unique_timestamp_ventilator_combination'),
        ),
        migrations.AddConstraint(
            model_name='peopleinroom',
            constraint=models.UniqueConstraint(fields=('timestamp', 'room'), name='unique_timestamp_room_combination'),
        ),
        migrations.AddConstraint(
            model_name='dooropen',
            constraint=models.UniqueConstraint(fields=('timestamp', 'door'), name='unique_timestamp_door_combination'),
        ),
    ]
