# Generated by Django 3.2.17 on 2023-11-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Door', max_length=30)),
                ('bloqueada', models.BooleanField(default=False)),
                ('isOpen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Light', max_length=30)),
                ('isOn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('size', models.FloatField()),
                ('doorNumber', models.FloatField(default=0)),
                ('windowNumber', models.FloatField(default=0)),
                ('lightsBool', models.BooleanField(default=False)),
                ('ventilatorBool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ventilator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Ventilator', max_length=30)),
                ('isOn', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.room')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Window', max_length=30)),
                ('isOpen', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.room')),
            ],
        ),
        migrations.CreateModel(
            name='WindowOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('isOpen', models.BooleanField(default=False)),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.window')),
            ],
        ),
        migrations.CreateModel(
            name='VentilatorIsOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('isOn', models.BooleanField(default=False)),
                ('ventilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ventilator')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('people', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('co2', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.room')),
            ],
        ),
        migrations.CreateModel(
            name='LightIsOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('isOn', models.BooleanField(default=False)),
                ('light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.light')),
            ],
        ),
        migrations.AddField(
            model_name='light',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.room'),
        ),
        migrations.CreateModel(
            name='DoorOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('isOpen', models.BooleanField(default=False)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.door')),
            ],
        ),
        migrations.AddField(
            model_name='door',
            name='rooms',
            field=models.ManyToManyField(to='project.Room'),
        ),
        migrations.AddConstraint(
            model_name='windowopen',
            constraint=models.UniqueConstraint(fields=('timestamp', 'window'), name='unique_timestamp_window_combination'),
        ),
        migrations.AddConstraint(
            model_name='ventilatorison',
            constraint=models.UniqueConstraint(fields=('timestamp', 'ventilator'), name='unique_timestamp_ventilator_combination'),
        ),
        migrations.AddConstraint(
            model_name='roomtemperature',
            constraint=models.UniqueConstraint(fields=('timestamp', 'room'), name='unique_timestamp_room_temperature_combination'),
        ),
        migrations.AddConstraint(
            model_name='roompeople',
            constraint=models.UniqueConstraint(fields=('timestamp', 'room'), name='unique_timestamp_room_combination'),
        ),
        migrations.AddConstraint(
            model_name='roomco2',
            constraint=models.UniqueConstraint(fields=('timestamp', 'room'), name='unique_timestamp_room_co2_combination'),
        ),
        migrations.AddConstraint(
            model_name='lightison',
            constraint=models.UniqueConstraint(fields=('timestamp', 'light'), name='unique_timestamp_light_combination'),
        ),
        migrations.AddConstraint(
            model_name='dooropen',
            constraint=models.UniqueConstraint(fields=('timestamp', 'door'), name='unique_timestamp_door_combination'),
        ),
    ]
