# Generated by Django 3.2.17 on 2023-10-30 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20231029_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.room')),
            ],
        ),
        migrations.AddConstraint(
            model_name='roomtemperature',
            constraint=models.UniqueConstraint(fields=('timestamp', 'room'), name='unique_timestamp_room_temperature_combination'),
        ),
    ]
