# Generated by Django 3.2.17 on 2023-10-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20231030_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtemperature',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
