# Generated by Django 3.2.17 on 2023-10-30 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_roomtemperature_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinroom',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='RoomCO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('co2', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.room')),
            ],
        ),
        migrations.AddConstraint(
            model_name='roomco2',
            constraint=models.UniqueConstraint(fields=('timestamp', 'room'), name='unique_timestamp_room_co2_combination'),
        ),
    ]
