# Generated by Django 3.2.17 on 2023-10-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20231030_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('people', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='NOPeopleInRoom',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='temperatura',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='room',
            name='luz',
        ),
        migrations.DeleteModel(
            name='PeopleInRoom',
        ),
        migrations.AddField(
            model_name='roompeople',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.room'),
        ),
        migrations.AddConstraint(
            model_name='roompeople',
            constraint=models.UniqueConstraint(fields=('timestamp', 'room'), name='unique_timestamp_room_combination'),
        ),
    ]
