# Generated by Django 3.2.17 on 2023-10-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20231030_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('isOn', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='co2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='people',
        ),
        migrations.RemoveField(
            model_name='room',
            name='temperature',
        ),
        migrations.CreateModel(
            name='LightIsOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('isOn', models.BooleanField()),
                ('light', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.light')),
            ],
        ),
        migrations.AddField(
            model_name='light',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.room'),
        ),
        migrations.AddConstraint(
            model_name='lightison',
            constraint=models.UniqueConstraint(fields=('timestamp', 'light'), name='unique_timestamp_light_combination'),
        ),
    ]
