# Generated by Django 3.2.17 on 2023-10-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20231030_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='name',
            field=models.CharField(default='Door', max_length=30),
        ),
        migrations.AddField(
            model_name='light',
            name='name',
            field=models.CharField(default='Light', max_length=30),
        ),
        migrations.AddField(
            model_name='ventilator',
            name='name',
            field=models.CharField(default='Ventilator', max_length=30),
        ),
        migrations.AddField(
            model_name='window',
            name='name',
            field=models.CharField(default='Window', max_length=30),
        ),
    ]
