# Generated by Django 3.2.17 on 2023-11-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20231106_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dooropen',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='windowopen',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
    ]
